reviews_pipeline_orchestration:
  outputs:
    dev:
      account: CETQJVF-SN29629
      database: CAPSTONE_AMAZON_DB
      private_key: "{{ env_var('SNOWFLAKE_PRIVATE_KEY') }}"
      role: ACCOUNTADMIN
      schema: CAPSTONE_AMAZON_RAW
      threads: 4
      type: snowflake
      user: DEELENV
      warehouse: SNOWFLAKE_LEARNING_WH
  target: dev
